#!/bin/sh
valid_email="mike@knights.ucf.edu"
invalid_email="Mike@knights.ucf.edu"
password="welcome" 
login_url="localhost:5000/login"

curl -o /dev/null --silent -c valid.cookie -X POST -F email="$valid_email" -F password=welcome "$login_url"
curl -o /dev/null --silent -c invalid.cookie -X POST -F email="$invalid_email" -F password=welcome "$login_url"
